import {StyleSheet} from 'react-native';
import {colors, family, HP, size, WP} from '../../../../utilities';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: HP(6),
    flexGrow: 1,
  },
  heroWrap: {
    width: '100%',
    height: 280,
    backgroundColor: colors.g15,
  },
  heroImage: {
    width: '100%',
    height: '100%',
  },
  heroOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.25)',
  },
  headerSafe: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: WP(4),
    paddingTop: HP(0.5),
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.9)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  backIcon: {
    width: 24,
    height: 24,
    tintColor: colors.b1,
  },
  contentCard: {
    marginTop: -24,
    marginHorizontal: WP(4),
    backgroundColor: colors.white,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.g15,
    paddingHorizontal: WP(5),
    paddingTop: HP(2.5),
    paddingBottom: HP(4),
    shadowColor: colors.b1,
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 8,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginBottom: HP(1.3),
    gap: 8,
  },
  readTimeChip: {
    backgroundColor: colors.p12,
    paddingHorizontal: WP(3),
    paddingVertical: HP(0.6),
    borderRadius: 8,
  },
  readTimeText: {
    fontSize: size.small,
    fontFamily: family.inter_bold,
    color: colors.p2,
  },
  insightBadge: {
    backgroundColor: colors.g15,
    paddingHorizontal: WP(3),
    paddingVertical: HP(0.6),
    borderRadius: 8,
  },
  insightBadgeText: {
    fontSize: size.small,
    fontFamily: family.inter_medium,
    color: colors.g1,
  },
  featuredChip: {
    backgroundColor: colors.p1,
    paddingHorizontal: WP(3),
    paddingVertical: HP(0.6),
    borderRadius: 8,
  },
  featuredChipText: {
    fontSize: size.small,
    fontFamily: family.inter_bold,
    color: colors.white,
  },
  insightTitle: {
    fontSize: 22,
    fontFamily: family.inter_bold,
    fontWeight: '700',
    color: colors.b1,
    lineHeight: 31,
    letterSpacing: -0.3,
    flex: 1,
  },
  titleBlock: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: WP(2.2),
    marginBottom: HP(1.1),
  },
  titleAccent: {
    width: WP(1.1),
    height: HP(4),
    borderRadius: WP(1),
    backgroundColor: colors.p1,
    marginTop: HP(0.2),
  },
  bylineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: HP(1.8),
    width: '100%',
  },
  authorChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EEF2FF',
    borderWidth: 1,
    borderColor: '#D9E1FF',
    paddingHorizontal: WP(2.6),
    paddingVertical: HP(0.45),
    borderRadius: WP(8),
    gap: WP(1.3),
  },
  authorLabel: {
    fontSize: size.xxtiny,
    fontFamily: family.inter_bold,
    color: colors.p2,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  authorNameText: {
    fontSize: size.small,
    fontFamily: family.inter_bold,
    color: colors.b1,
  },
  dateChip: {
    backgroundColor: colors.p12,
    borderWidth: 1,
    borderColor: '#DCE4FF',
    paddingHorizontal: WP(2.6),
    paddingVertical: HP(0.45),
    borderRadius: WP(8),
    marginLeft: WP(2),
  },
  dateChipText: {
    fontSize: size.xtiny,
    fontFamily: family.inter_bold,
    color: colors.p2,
  },
  divider: {
    width: 48,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.p1,
    marginBottom: HP(2.5),
    opacity: 0.9,
  },
  description: {
    fontSize: size.normal,
    fontFamily: family.inter_regular,
    color: colors.g1,
    lineHeight: 27,
    letterSpacing: 0.1,
  },
});

export default styles;
